/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graphql Scalar Type Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlScalarTypeDefinition()
 * @model
 * @generated
 */
public interface GraphqlScalarTypeDefinition extends GraphqlTypeDefinition
{
} // GraphqlScalarTypeDefinition
