/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graphql Schema Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getName <em>Name</em>}</li>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getRootQuery <em>Root Query</em>}</li>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getMutation <em>Mutation</em>}</li>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getSubcription <em>Subcription</em>}</li>
 * </ul>
 *
 * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlSchemaDefinition()
 * @model
 * @generated
 */
public interface GraphqlSchemaDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlSchemaDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Root Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Root Query</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Root Query</em>' containment reference.
   * @see #setRootQuery(GraphqlRootQuery)
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlSchemaDefinition_RootQuery()
   * @model containment="true"
   * @generated
   */
  GraphqlRootQuery getRootQuery();

  /**
   * Sets the value of the '{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getRootQuery <em>Root Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Root Query</em>' containment reference.
   * @see #getRootQuery()
   * @generated
   */
  void setRootQuery(GraphqlRootQuery value);

  /**
   * Returns the value of the '<em><b>Mutation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mutation</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mutation</em>' reference.
   * @see #setMutation(GraphqlObjectTypeDefinition)
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlSchemaDefinition_Mutation()
   * @model
   * @generated
   */
  GraphqlObjectTypeDefinition getMutation();

  /**
   * Sets the value of the '{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getMutation <em>Mutation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mutation</em>' reference.
   * @see #getMutation()
   * @generated
   */
  void setMutation(GraphqlObjectTypeDefinition value);

  /**
   * Returns the value of the '<em><b>Subcription</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Subcription</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subcription</em>' reference.
   * @see #setSubcription(GraphqlObjectTypeDefinition)
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlSchemaDefinition_Subcription()
   * @model
   * @generated
   */
  GraphqlObjectTypeDefinition getSubcription();

  /**
   * Sets the value of the '{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getSubcription <em>Subcription</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subcription</em>' reference.
   * @see #getSubcription()
   * @generated
   */
  void setSubcription(GraphqlObjectTypeDefinition value);

} // GraphqlSchemaDefinition
