/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graphql Schema</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlSchema#getSchema <em>Schema</em>}</li>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlSchema#getTypes <em>Types</em>}</li>
 * </ul>
 *
 * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlSchema()
 * @model
 * @generated
 */
public interface GraphqlSchema extends EObject
{
  /**
   * Returns the value of the '<em><b>Schema</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Schema</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Schema</em>' containment reference.
   * @see #setSchema(GraphqlSchemaDefinition)
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlSchema_Schema()
   * @model containment="true"
   * @generated
   */
  GraphqlSchemaDefinition getSchema();

  /**
   * Sets the value of the '{@link oda.graphql.language.graphqlidl.GraphqlSchema#getSchema <em>Schema</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Schema</em>' containment reference.
   * @see #getSchema()
   * @generated
   */
  void setSchema(GraphqlSchemaDefinition value);

  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link oda.graphql.language.graphqlidl.GraphqlTypeDefinition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlSchema_Types()
   * @model containment="true"
   * @generated
   */
  EList<GraphqlTypeDefinition> getTypes();

} // GraphqlSchema
