/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graphql List Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlListType()
 * @model
 * @generated
 */
public interface GraphqlListType extends EObject
{
} // GraphqlListType
