/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see oda.graphql.language.graphqlidl.GraphqlidlPackage
 * @generated
 */
public interface GraphqlidlFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GraphqlidlFactory eINSTANCE = oda.graphql.language.graphqlidl.impl.GraphqlidlFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Graphql Schema</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Schema</em>'.
   * @generated
   */
  GraphqlSchema createGraphqlSchema();

  /**
   * Returns a new object of class '<em>Graphql Schema Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Schema Definition</em>'.
   * @generated
   */
  GraphqlSchemaDefinition createGraphqlSchemaDefinition();

  /**
   * Returns a new object of class '<em>Graphql Root Query</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Root Query</em>'.
   * @generated
   */
  GraphqlRootQuery createGraphqlRootQuery();

  /**
   * Returns a new object of class '<em>Graphql Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Type Definition</em>'.
   * @generated
   */
  GraphqlTypeDefinition createGraphqlTypeDefinition();

  /**
   * Returns a new object of class '<em>Graphql Object Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Object Type Definition</em>'.
   * @generated
   */
  GraphqlObjectTypeDefinition createGraphqlObjectTypeDefinition();

  /**
   * Returns a new object of class '<em>Graphql Interface Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Interface Type Definition</em>'.
   * @generated
   */
  GraphqlInterfaceTypeDefinition createGraphqlInterfaceTypeDefinition();

  /**
   * Returns a new object of class '<em>Graphql Scalar Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Scalar Type Definition</em>'.
   * @generated
   */
  GraphqlScalarTypeDefinition createGraphqlScalarTypeDefinition();

  /**
   * Returns a new object of class '<em>Graphql Emun Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Emun Type Definition</em>'.
   * @generated
   */
  GraphqlEmunTypeDefinition createGraphqlEmunTypeDefinition();

  /**
   * Returns a new object of class '<em>Graphql Union Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Union Type Definition</em>'.
   * @generated
   */
  GraphqlUnionTypeDefinition createGraphqlUnionTypeDefinition();

  /**
   * Returns a new object of class '<em>Graphql Input Type Definition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Input Type Definition</em>'.
   * @generated
   */
  GraphqlInputTypeDefinition createGraphqlInputTypeDefinition();

  /**
   * Returns a new object of class '<em>Graphql Input Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Input Field</em>'.
   * @generated
   */
  GraphqlInputField createGraphqlInputField();

  /**
   * Returns a new object of class '<em>Graphql Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Field</em>'.
   * @generated
   */
  GraphqlField createGraphqlField();

  /**
   * Returns a new object of class '<em>Graphql Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Type</em>'.
   * @generated
   */
  GraphqlType createGraphqlType();

  /**
   * Returns a new object of class '<em>Graphql Named Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Named Type</em>'.
   * @generated
   */
  GraphqlNamedType createGraphqlNamedType();

  /**
   * Returns a new object of class '<em>Graphql List Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql List Type</em>'.
   * @generated
   */
  GraphqlListType createGraphqlListType();

  /**
   * Returns a new object of class '<em>Graphql Input Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Input Type</em>'.
   * @generated
   */
  GraphqlInputType createGraphqlInputType();

  /**
   * Returns a new object of class '<em>Graphql List Input Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql List Input Type</em>'.
   * @generated
   */
  GraphqlListInputType createGraphqlListInputType();

  /**
   * Returns a new object of class '<em>Argument</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Argument</em>'.
   * @generated
   */
  Argument createArgument();

  /**
   * Returns a new object of class '<em>Graphql Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Graphql Value</em>'.
   * @generated
   */
  GraphqlValue createGraphqlValue();

  /**
   * Returns a new object of class '<em>Single Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Single Value</em>'.
   * @generated
   */
  SingleValue createSingleValue();

  /**
   * Returns a new object of class '<em>Complex Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Complex Value</em>'.
   * @generated
   */
  ComplexValue createComplexValue();

  /**
   * Returns a new object of class '<em>Enum Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enum Value</em>'.
   * @generated
   */
  EnumValue createEnumValue();

  /**
   * Returns a new object of class '<em>List Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>List Value</em>'.
   * @generated
   */
  ListValue createListValue();

  /**
   * Returns a new object of class '<em>Object Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Value</em>'.
   * @generated
   */
  ObjectValue createObjectValue();

  /**
   * Returns a new object of class '<em>Object Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Object Field</em>'.
   * @generated
   */
  ObjectField createObjectField();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GraphqlidlPackage getGraphqlidlPackage();

} //GraphqlidlFactory
