/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graphql Root Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlRootQuery#getName <em>Name</em>}</li>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlRootQuery#getQuery <em>Query</em>}</li>
 * </ul>
 *
 * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlRootQuery()
 * @model
 * @generated
 */
public interface GraphqlRootQuery extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlRootQuery_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link oda.graphql.language.graphqlidl.GraphqlRootQuery#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Query</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Query</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query</em>' reference.
   * @see #setQuery(GraphqlObjectTypeDefinition)
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlRootQuery_Query()
   * @model
   * @generated
   */
  GraphqlObjectTypeDefinition getQuery();

  /**
   * Sets the value of the '{@link oda.graphql.language.graphqlidl.GraphqlRootQuery#getQuery <em>Query</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Query</em>' reference.
   * @see #getQuery()
   * @generated
   */
  void setQuery(GraphqlObjectTypeDefinition value);

} // GraphqlRootQuery
