/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graphql Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlField#getName <em>Name</em>}</li>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlField#getArgs <em>Args</em>}</li>
 *   <li>{@link oda.graphql.language.graphqlidl.GraphqlField#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlField()
 * @model
 * @generated
 */
public interface GraphqlField extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlField_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link oda.graphql.language.graphqlidl.GraphqlField#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link oda.graphql.language.graphqlidl.Argument}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlField_Args()
   * @model containment="true"
   * @generated
   */
  EList<Argument> getArgs();

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(GraphqlType)
   * @see oda.graphql.language.graphqlidl.GraphqlidlPackage#getGraphqlField_Type()
   * @model containment="true"
   * @generated
   */
  GraphqlType getType();

  /**
   * Sets the value of the '{@link oda.graphql.language.graphqlidl.GraphqlField#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(GraphqlType value);

} // GraphqlField
