/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see oda.graphql.language.graphqlidl.GraphqlidlFactory
 * @model kind="package"
 * @generated
 */
public interface GraphqlidlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "graphqlidl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.graphql.oda/language/Graphqlidl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "graphqlidl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GraphqlidlPackage eINSTANCE = oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl.init();

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlSchemaImpl <em>Graphql Schema</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlSchemaImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlSchema()
   * @generated
   */
  int GRAPHQL_SCHEMA = 0;

  /**
   * The feature id for the '<em><b>Schema</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCHEMA__SCHEMA = 0;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCHEMA__TYPES = 1;

  /**
   * The number of structural features of the '<em>Graphql Schema</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCHEMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlSchemaDefinitionImpl <em>Graphql Schema Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlSchemaDefinitionImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlSchemaDefinition()
   * @generated
   */
  int GRAPHQL_SCHEMA_DEFINITION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCHEMA_DEFINITION__NAME = 0;

  /**
   * The feature id for the '<em><b>Root Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCHEMA_DEFINITION__ROOT_QUERY = 1;

  /**
   * The feature id for the '<em><b>Mutation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCHEMA_DEFINITION__MUTATION = 2;

  /**
   * The feature id for the '<em><b>Subcription</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCHEMA_DEFINITION__SUBCRIPTION = 3;

  /**
   * The number of structural features of the '<em>Graphql Schema Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCHEMA_DEFINITION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlRootQueryImpl <em>Graphql Root Query</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlRootQueryImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlRootQuery()
   * @generated
   */
  int GRAPHQL_ROOT_QUERY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_ROOT_QUERY__NAME = 0;

  /**
   * The feature id for the '<em><b>Query</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_ROOT_QUERY__QUERY = 1;

  /**
   * The number of structural features of the '<em>Graphql Root Query</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_ROOT_QUERY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlTypeDefinitionImpl <em>Graphql Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlTypeDefinitionImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlTypeDefinition()
   * @generated
   */
  int GRAPHQL_TYPE_DEFINITION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_TYPE_DEFINITION__NAME = 0;

  /**
   * The number of structural features of the '<em>Graphql Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlObjectTypeDefinitionImpl <em>Graphql Object Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlObjectTypeDefinitionImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlObjectTypeDefinition()
   * @generated
   */
  int GRAPHQL_OBJECT_TYPE_DEFINITION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_OBJECT_TYPE_DEFINITION__NAME = GRAPHQL_TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Interfaces</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_OBJECT_TYPE_DEFINITION__INTERFACES = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_OBJECT_TYPE_DEFINITION__FIELDS = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Graphql Object Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_OBJECT_TYPE_DEFINITION_FEATURE_COUNT = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlInterfaceTypeDefinitionImpl <em>Graphql Interface Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlInterfaceTypeDefinitionImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlInterfaceTypeDefinition()
   * @generated
   */
  int GRAPHQL_INTERFACE_TYPE_DEFINITION = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INTERFACE_TYPE_DEFINITION__NAME = GRAPHQL_TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INTERFACE_TYPE_DEFINITION__FIELDS = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Graphql Interface Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INTERFACE_TYPE_DEFINITION_FEATURE_COUNT = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlScalarTypeDefinitionImpl <em>Graphql Scalar Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlScalarTypeDefinitionImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlScalarTypeDefinition()
   * @generated
   */
  int GRAPHQL_SCALAR_TYPE_DEFINITION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCALAR_TYPE_DEFINITION__NAME = GRAPHQL_TYPE_DEFINITION__NAME;

  /**
   * The number of structural features of the '<em>Graphql Scalar Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_SCALAR_TYPE_DEFINITION_FEATURE_COUNT = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlEmunTypeDefinitionImpl <em>Graphql Emun Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlEmunTypeDefinitionImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlEmunTypeDefinition()
   * @generated
   */
  int GRAPHQL_EMUN_TYPE_DEFINITION = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_EMUN_TYPE_DEFINITION__NAME = GRAPHQL_TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_EMUN_TYPE_DEFINITION__VALUES = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Graphql Emun Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_EMUN_TYPE_DEFINITION_FEATURE_COUNT = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlUnionTypeDefinitionImpl <em>Graphql Union Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlUnionTypeDefinitionImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlUnionTypeDefinition()
   * @generated
   */
  int GRAPHQL_UNION_TYPE_DEFINITION = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_UNION_TYPE_DEFINITION__NAME = GRAPHQL_TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Members</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_UNION_TYPE_DEFINITION__MEMBERS = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Graphql Union Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_UNION_TYPE_DEFINITION_FEATURE_COUNT = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlInputTypeDefinitionImpl <em>Graphql Input Type Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlInputTypeDefinitionImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlInputTypeDefinition()
   * @generated
   */
  int GRAPHQL_INPUT_TYPE_DEFINITION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_TYPE_DEFINITION__NAME = GRAPHQL_TYPE_DEFINITION__NAME;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_TYPE_DEFINITION__FIELDS = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Graphql Input Type Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_TYPE_DEFINITION_FEATURE_COUNT = GRAPHQL_TYPE_DEFINITION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlInputFieldImpl <em>Graphql Input Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlInputFieldImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlInputField()
   * @generated
   */
  int GRAPHQL_INPUT_FIELD = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_FIELD__TYPE = 1;

  /**
   * The number of structural features of the '<em>Graphql Input Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_FIELD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlFieldImpl <em>Graphql Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlFieldImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlField()
   * @generated
   */
  int GRAPHQL_FIELD = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Args</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_FIELD__ARGS = 1;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_FIELD__TYPE = 2;

  /**
   * The number of structural features of the '<em>Graphql Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_FIELD_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlListTypeImpl <em>Graphql List Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlListTypeImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlListType()
   * @generated
   */
  int GRAPHQL_LIST_TYPE = 14;

  /**
   * The number of structural features of the '<em>Graphql List Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_LIST_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlTypeImpl <em>Graphql Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlTypeImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlType()
   * @generated
   */
  int GRAPHQL_TYPE = 12;

  /**
   * The feature id for the '<em><b>Dtype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_TYPE__DTYPE = GRAPHQL_LIST_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Non Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_TYPE__NON_NULL = GRAPHQL_LIST_TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Ntype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_TYPE__NTYPE = GRAPHQL_LIST_TYPE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Ltype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_TYPE__LTYPE = GRAPHQL_LIST_TYPE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Graphql Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_TYPE_FEATURE_COUNT = GRAPHQL_LIST_TYPE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlNamedTypeImpl <em>Graphql Named Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlNamedTypeImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlNamedType()
   * @generated
   */
  int GRAPHQL_NAMED_TYPE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_NAMED_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Graphql Named Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_NAMED_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlListInputTypeImpl <em>Graphql List Input Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlListInputTypeImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlListInputType()
   * @generated
   */
  int GRAPHQL_LIST_INPUT_TYPE = 16;

  /**
   * The number of structural features of the '<em>Graphql List Input Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_LIST_INPUT_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlInputTypeImpl <em>Graphql Input Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlInputTypeImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlInputType()
   * @generated
   */
  int GRAPHQL_INPUT_TYPE = 15;

  /**
   * The feature id for the '<em><b>Dtype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_TYPE__DTYPE = GRAPHQL_LIST_INPUT_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Non Null</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_TYPE__NON_NULL = GRAPHQL_LIST_INPUT_TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Ntype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_TYPE__NTYPE = GRAPHQL_LIST_INPUT_TYPE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Ltype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_TYPE__LTYPE = GRAPHQL_LIST_INPUT_TYPE_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Graphql Input Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_INPUT_TYPE_FEATURE_COUNT = GRAPHQL_LIST_INPUT_TYPE_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.ArgumentImpl <em>Argument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.ArgumentImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getArgument()
   * @generated
   */
  int ARGUMENT = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT__TYPE = 1;

  /**
   * The feature id for the '<em><b>Def Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT__DEF_VALUE = 2;

  /**
   * The number of structural features of the '<em>Argument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARGUMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlValueImpl <em>Graphql Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.GraphqlValueImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlValue()
   * @generated
   */
  int GRAPHQL_VALUE = 18;

  /**
   * The feature id for the '<em><b>Sv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_VALUE__SV = 0;

  /**
   * The feature id for the '<em><b>Ev</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_VALUE__EV = 1;

  /**
   * The feature id for the '<em><b>Cv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_VALUE__CV = 2;

  /**
   * The number of structural features of the '<em>Graphql Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPHQL_VALUE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.SingleValueImpl <em>Single Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.SingleValueImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getSingleValue()
   * @generated
   */
  int SINGLE_VALUE = 19;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Single Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.ComplexValueImpl <em>Complex Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.ComplexValueImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getComplexValue()
   * @generated
   */
  int COMPLEX_VALUE = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Complex Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.EnumValueImpl <em>Enum Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.EnumValueImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getEnumValue()
   * @generated
   */
  int ENUM_VALUE = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE__NAME = 0;

  /**
   * The number of structural features of the '<em>Enum Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENUM_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.ListValueImpl <em>List Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.ListValueImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getListValue()
   * @generated
   */
  int LIST_VALUE = 22;

  /**
   * The feature id for the '<em><b>Values</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_VALUE__VALUES = 0;

  /**
   * The number of structural features of the '<em>List Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIST_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.ObjectValueImpl <em>Object Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.ObjectValueImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getObjectValue()
   * @generated
   */
  int OBJECT_VALUE = 23;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_VALUE__FIELDS = 0;

  /**
   * The number of structural features of the '<em>Object Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link oda.graphql.language.graphqlidl.impl.ObjectFieldImpl <em>Object Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oda.graphql.language.graphqlidl.impl.ObjectFieldImpl
   * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getObjectField()
   * @generated
   */
  int OBJECT_FIELD = 24;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FIELD__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FIELD__VALUE = 1;

  /**
   * The number of structural features of the '<em>Object Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_FIELD_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlSchema <em>Graphql Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Schema</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlSchema
   * @generated
   */
  EClass getGraphqlSchema();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlSchema#getSchema <em>Schema</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Schema</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlSchema#getSchema()
   * @see #getGraphqlSchema()
   * @generated
   */
  EReference getGraphqlSchema_Schema();

  /**
   * Returns the meta object for the containment reference list '{@link oda.graphql.language.graphqlidl.GraphqlSchema#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlSchema#getTypes()
   * @see #getGraphqlSchema()
   * @generated
   */
  EReference getGraphqlSchema_Types();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition <em>Graphql Schema Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Schema Definition</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlSchemaDefinition
   * @generated
   */
  EClass getGraphqlSchemaDefinition();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getName()
   * @see #getGraphqlSchemaDefinition()
   * @generated
   */
  EAttribute getGraphqlSchemaDefinition_Name();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getRootQuery <em>Root Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Root Query</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getRootQuery()
   * @see #getGraphqlSchemaDefinition()
   * @generated
   */
  EReference getGraphqlSchemaDefinition_RootQuery();

  /**
   * Returns the meta object for the reference '{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getMutation <em>Mutation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Mutation</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getMutation()
   * @see #getGraphqlSchemaDefinition()
   * @generated
   */
  EReference getGraphqlSchemaDefinition_Mutation();

  /**
   * Returns the meta object for the reference '{@link oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getSubcription <em>Subcription</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Subcription</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlSchemaDefinition#getSubcription()
   * @see #getGraphqlSchemaDefinition()
   * @generated
   */
  EReference getGraphqlSchemaDefinition_Subcription();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlRootQuery <em>Graphql Root Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Root Query</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlRootQuery
   * @generated
   */
  EClass getGraphqlRootQuery();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.GraphqlRootQuery#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlRootQuery#getName()
   * @see #getGraphqlRootQuery()
   * @generated
   */
  EAttribute getGraphqlRootQuery_Name();

  /**
   * Returns the meta object for the reference '{@link oda.graphql.language.graphqlidl.GraphqlRootQuery#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Query</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlRootQuery#getQuery()
   * @see #getGraphqlRootQuery()
   * @generated
   */
  EReference getGraphqlRootQuery_Query();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlTypeDefinition <em>Graphql Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Type Definition</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlTypeDefinition
   * @generated
   */
  EClass getGraphqlTypeDefinition();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.GraphqlTypeDefinition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlTypeDefinition#getName()
   * @see #getGraphqlTypeDefinition()
   * @generated
   */
  EAttribute getGraphqlTypeDefinition_Name();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlObjectTypeDefinition <em>Graphql Object Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Object Type Definition</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlObjectTypeDefinition
   * @generated
   */
  EClass getGraphqlObjectTypeDefinition();

  /**
   * Returns the meta object for the reference list '{@link oda.graphql.language.graphqlidl.GraphqlObjectTypeDefinition#getInterfaces <em>Interfaces</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Interfaces</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlObjectTypeDefinition#getInterfaces()
   * @see #getGraphqlObjectTypeDefinition()
   * @generated
   */
  EReference getGraphqlObjectTypeDefinition_Interfaces();

  /**
   * Returns the meta object for the containment reference list '{@link oda.graphql.language.graphqlidl.GraphqlObjectTypeDefinition#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlObjectTypeDefinition#getFields()
   * @see #getGraphqlObjectTypeDefinition()
   * @generated
   */
  EReference getGraphqlObjectTypeDefinition_Fields();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlInterfaceTypeDefinition <em>Graphql Interface Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Interface Type Definition</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInterfaceTypeDefinition
   * @generated
   */
  EClass getGraphqlInterfaceTypeDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link oda.graphql.language.graphqlidl.GraphqlInterfaceTypeDefinition#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInterfaceTypeDefinition#getFields()
   * @see #getGraphqlInterfaceTypeDefinition()
   * @generated
   */
  EReference getGraphqlInterfaceTypeDefinition_Fields();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlScalarTypeDefinition <em>Graphql Scalar Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Scalar Type Definition</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlScalarTypeDefinition
   * @generated
   */
  EClass getGraphqlScalarTypeDefinition();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlEmunTypeDefinition <em>Graphql Emun Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Emun Type Definition</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlEmunTypeDefinition
   * @generated
   */
  EClass getGraphqlEmunTypeDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link oda.graphql.language.graphqlidl.GraphqlEmunTypeDefinition#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlEmunTypeDefinition#getValues()
   * @see #getGraphqlEmunTypeDefinition()
   * @generated
   */
  EReference getGraphqlEmunTypeDefinition_Values();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlUnionTypeDefinition <em>Graphql Union Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Union Type Definition</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlUnionTypeDefinition
   * @generated
   */
  EClass getGraphqlUnionTypeDefinition();

  /**
   * Returns the meta object for the reference list '{@link oda.graphql.language.graphqlidl.GraphqlUnionTypeDefinition#getMembers <em>Members</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Members</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlUnionTypeDefinition#getMembers()
   * @see #getGraphqlUnionTypeDefinition()
   * @generated
   */
  EReference getGraphqlUnionTypeDefinition_Members();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlInputTypeDefinition <em>Graphql Input Type Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Input Type Definition</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputTypeDefinition
   * @generated
   */
  EClass getGraphqlInputTypeDefinition();

  /**
   * Returns the meta object for the containment reference list '{@link oda.graphql.language.graphqlidl.GraphqlInputTypeDefinition#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputTypeDefinition#getFields()
   * @see #getGraphqlInputTypeDefinition()
   * @generated
   */
  EReference getGraphqlInputTypeDefinition_Fields();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlInputField <em>Graphql Input Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Input Field</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputField
   * @generated
   */
  EClass getGraphqlInputField();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.GraphqlInputField#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputField#getName()
   * @see #getGraphqlInputField()
   * @generated
   */
  EAttribute getGraphqlInputField_Name();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlInputField#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputField#getType()
   * @see #getGraphqlInputField()
   * @generated
   */
  EReference getGraphqlInputField_Type();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlField <em>Graphql Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Field</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlField
   * @generated
   */
  EClass getGraphqlField();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.GraphqlField#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlField#getName()
   * @see #getGraphqlField()
   * @generated
   */
  EAttribute getGraphqlField_Name();

  /**
   * Returns the meta object for the containment reference list '{@link oda.graphql.language.graphqlidl.GraphqlField#getArgs <em>Args</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Args</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlField#getArgs()
   * @see #getGraphqlField()
   * @generated
   */
  EReference getGraphqlField_Args();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlField#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlField#getType()
   * @see #getGraphqlField()
   * @generated
   */
  EReference getGraphqlField_Type();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlType <em>Graphql Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Type</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlType
   * @generated
   */
  EClass getGraphqlType();

  /**
   * Returns the meta object for the reference '{@link oda.graphql.language.graphqlidl.GraphqlType#getDtype <em>Dtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Dtype</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlType#getDtype()
   * @see #getGraphqlType()
   * @generated
   */
  EReference getGraphqlType_Dtype();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.GraphqlType#isNonNull <em>Non Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Non Null</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlType#isNonNull()
   * @see #getGraphqlType()
   * @generated
   */
  EAttribute getGraphqlType_NonNull();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlType#getNtype <em>Ntype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ntype</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlType#getNtype()
   * @see #getGraphqlType()
   * @generated
   */
  EReference getGraphqlType_Ntype();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlType#getLtype <em>Ltype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ltype</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlType#getLtype()
   * @see #getGraphqlType()
   * @generated
   */
  EReference getGraphqlType_Ltype();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlNamedType <em>Graphql Named Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Named Type</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlNamedType
   * @generated
   */
  EClass getGraphqlNamedType();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.GraphqlNamedType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlNamedType#getName()
   * @see #getGraphqlNamedType()
   * @generated
   */
  EAttribute getGraphqlNamedType_Name();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlListType <em>Graphql List Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql List Type</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlListType
   * @generated
   */
  EClass getGraphqlListType();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlInputType <em>Graphql Input Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Input Type</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputType
   * @generated
   */
  EClass getGraphqlInputType();

  /**
   * Returns the meta object for the reference '{@link oda.graphql.language.graphqlidl.GraphqlInputType#getDtype <em>Dtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Dtype</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputType#getDtype()
   * @see #getGraphqlInputType()
   * @generated
   */
  EReference getGraphqlInputType_Dtype();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.GraphqlInputType#isNonNull <em>Non Null</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Non Null</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputType#isNonNull()
   * @see #getGraphqlInputType()
   * @generated
   */
  EAttribute getGraphqlInputType_NonNull();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlInputType#getNtype <em>Ntype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ntype</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputType#getNtype()
   * @see #getGraphqlInputType()
   * @generated
   */
  EReference getGraphqlInputType_Ntype();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlInputType#getLtype <em>Ltype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ltype</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlInputType#getLtype()
   * @see #getGraphqlInputType()
   * @generated
   */
  EReference getGraphqlInputType_Ltype();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlListInputType <em>Graphql List Input Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql List Input Type</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlListInputType
   * @generated
   */
  EClass getGraphqlListInputType();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.Argument <em>Argument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Argument</em>'.
   * @see oda.graphql.language.graphqlidl.Argument
   * @generated
   */
  EClass getArgument();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.Argument#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oda.graphql.language.graphqlidl.Argument#getName()
   * @see #getArgument()
   * @generated
   */
  EAttribute getArgument_Name();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.Argument#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see oda.graphql.language.graphqlidl.Argument#getType()
   * @see #getArgument()
   * @generated
   */
  EReference getArgument_Type();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.Argument#getDefValue <em>Def Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Def Value</em>'.
   * @see oda.graphql.language.graphqlidl.Argument#getDefValue()
   * @see #getArgument()
   * @generated
   */
  EReference getArgument_DefValue();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.GraphqlValue <em>Graphql Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graphql Value</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlValue
   * @generated
   */
  EClass getGraphqlValue();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlValue#getSv <em>Sv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sv</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlValue#getSv()
   * @see #getGraphqlValue()
   * @generated
   */
  EReference getGraphqlValue_Sv();

  /**
   * Returns the meta object for the reference '{@link oda.graphql.language.graphqlidl.GraphqlValue#getEv <em>Ev</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ev</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlValue#getEv()
   * @see #getGraphqlValue()
   * @generated
   */
  EReference getGraphqlValue_Ev();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.GraphqlValue#getCv <em>Cv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cv</em>'.
   * @see oda.graphql.language.graphqlidl.GraphqlValue#getCv()
   * @see #getGraphqlValue()
   * @generated
   */
  EReference getGraphqlValue_Cv();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.SingleValue <em>Single Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Value</em>'.
   * @see oda.graphql.language.graphqlidl.SingleValue
   * @generated
   */
  EClass getSingleValue();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.SingleValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see oda.graphql.language.graphqlidl.SingleValue#getValue()
   * @see #getSingleValue()
   * @generated
   */
  EAttribute getSingleValue_Value();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.ComplexValue <em>Complex Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Value</em>'.
   * @see oda.graphql.language.graphqlidl.ComplexValue
   * @generated
   */
  EClass getComplexValue();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.ComplexValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see oda.graphql.language.graphqlidl.ComplexValue#getValue()
   * @see #getComplexValue()
   * @generated
   */
  EReference getComplexValue_Value();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.EnumValue <em>Enum Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enum Value</em>'.
   * @see oda.graphql.language.graphqlidl.EnumValue
   * @generated
   */
  EClass getEnumValue();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.EnumValue#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oda.graphql.language.graphqlidl.EnumValue#getName()
   * @see #getEnumValue()
   * @generated
   */
  EAttribute getEnumValue_Name();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.ListValue <em>List Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>List Value</em>'.
   * @see oda.graphql.language.graphqlidl.ListValue
   * @generated
   */
  EClass getListValue();

  /**
   * Returns the meta object for the containment reference list '{@link oda.graphql.language.graphqlidl.ListValue#getValues <em>Values</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Values</em>'.
   * @see oda.graphql.language.graphqlidl.ListValue#getValues()
   * @see #getListValue()
   * @generated
   */
  EReference getListValue_Values();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.ObjectValue <em>Object Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Value</em>'.
   * @see oda.graphql.language.graphqlidl.ObjectValue
   * @generated
   */
  EClass getObjectValue();

  /**
   * Returns the meta object for the containment reference list '{@link oda.graphql.language.graphqlidl.ObjectValue#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see oda.graphql.language.graphqlidl.ObjectValue#getFields()
   * @see #getObjectValue()
   * @generated
   */
  EReference getObjectValue_Fields();

  /**
   * Returns the meta object for class '{@link oda.graphql.language.graphqlidl.ObjectField <em>Object Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Field</em>'.
   * @see oda.graphql.language.graphqlidl.ObjectField
   * @generated
   */
  EClass getObjectField();

  /**
   * Returns the meta object for the attribute '{@link oda.graphql.language.graphqlidl.ObjectField#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oda.graphql.language.graphqlidl.ObjectField#getName()
   * @see #getObjectField()
   * @generated
   */
  EAttribute getObjectField_Name();

  /**
   * Returns the meta object for the containment reference '{@link oda.graphql.language.graphqlidl.ObjectField#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see oda.graphql.language.graphqlidl.ObjectField#getValue()
   * @see #getObjectField()
   * @generated
   */
  EReference getObjectField_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GraphqlidlFactory getGraphqlidlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlSchemaImpl <em>Graphql Schema</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlSchemaImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlSchema()
     * @generated
     */
    EClass GRAPHQL_SCHEMA = eINSTANCE.getGraphqlSchema();

    /**
     * The meta object literal for the '<em><b>Schema</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_SCHEMA__SCHEMA = eINSTANCE.getGraphqlSchema_Schema();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_SCHEMA__TYPES = eINSTANCE.getGraphqlSchema_Types();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlSchemaDefinitionImpl <em>Graphql Schema Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlSchemaDefinitionImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlSchemaDefinition()
     * @generated
     */
    EClass GRAPHQL_SCHEMA_DEFINITION = eINSTANCE.getGraphqlSchemaDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHQL_SCHEMA_DEFINITION__NAME = eINSTANCE.getGraphqlSchemaDefinition_Name();

    /**
     * The meta object literal for the '<em><b>Root Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_SCHEMA_DEFINITION__ROOT_QUERY = eINSTANCE.getGraphqlSchemaDefinition_RootQuery();

    /**
     * The meta object literal for the '<em><b>Mutation</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_SCHEMA_DEFINITION__MUTATION = eINSTANCE.getGraphqlSchemaDefinition_Mutation();

    /**
     * The meta object literal for the '<em><b>Subcription</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_SCHEMA_DEFINITION__SUBCRIPTION = eINSTANCE.getGraphqlSchemaDefinition_Subcription();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlRootQueryImpl <em>Graphql Root Query</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlRootQueryImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlRootQuery()
     * @generated
     */
    EClass GRAPHQL_ROOT_QUERY = eINSTANCE.getGraphqlRootQuery();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHQL_ROOT_QUERY__NAME = eINSTANCE.getGraphqlRootQuery_Name();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_ROOT_QUERY__QUERY = eINSTANCE.getGraphqlRootQuery_Query();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlTypeDefinitionImpl <em>Graphql Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlTypeDefinitionImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlTypeDefinition()
     * @generated
     */
    EClass GRAPHQL_TYPE_DEFINITION = eINSTANCE.getGraphqlTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHQL_TYPE_DEFINITION__NAME = eINSTANCE.getGraphqlTypeDefinition_Name();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlObjectTypeDefinitionImpl <em>Graphql Object Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlObjectTypeDefinitionImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlObjectTypeDefinition()
     * @generated
     */
    EClass GRAPHQL_OBJECT_TYPE_DEFINITION = eINSTANCE.getGraphqlObjectTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Interfaces</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_OBJECT_TYPE_DEFINITION__INTERFACES = eINSTANCE.getGraphqlObjectTypeDefinition_Interfaces();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_OBJECT_TYPE_DEFINITION__FIELDS = eINSTANCE.getGraphqlObjectTypeDefinition_Fields();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlInterfaceTypeDefinitionImpl <em>Graphql Interface Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlInterfaceTypeDefinitionImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlInterfaceTypeDefinition()
     * @generated
     */
    EClass GRAPHQL_INTERFACE_TYPE_DEFINITION = eINSTANCE.getGraphqlInterfaceTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_INTERFACE_TYPE_DEFINITION__FIELDS = eINSTANCE.getGraphqlInterfaceTypeDefinition_Fields();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlScalarTypeDefinitionImpl <em>Graphql Scalar Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlScalarTypeDefinitionImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlScalarTypeDefinition()
     * @generated
     */
    EClass GRAPHQL_SCALAR_TYPE_DEFINITION = eINSTANCE.getGraphqlScalarTypeDefinition();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlEmunTypeDefinitionImpl <em>Graphql Emun Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlEmunTypeDefinitionImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlEmunTypeDefinition()
     * @generated
     */
    EClass GRAPHQL_EMUN_TYPE_DEFINITION = eINSTANCE.getGraphqlEmunTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_EMUN_TYPE_DEFINITION__VALUES = eINSTANCE.getGraphqlEmunTypeDefinition_Values();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlUnionTypeDefinitionImpl <em>Graphql Union Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlUnionTypeDefinitionImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlUnionTypeDefinition()
     * @generated
     */
    EClass GRAPHQL_UNION_TYPE_DEFINITION = eINSTANCE.getGraphqlUnionTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Members</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_UNION_TYPE_DEFINITION__MEMBERS = eINSTANCE.getGraphqlUnionTypeDefinition_Members();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlInputTypeDefinitionImpl <em>Graphql Input Type Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlInputTypeDefinitionImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlInputTypeDefinition()
     * @generated
     */
    EClass GRAPHQL_INPUT_TYPE_DEFINITION = eINSTANCE.getGraphqlInputTypeDefinition();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_INPUT_TYPE_DEFINITION__FIELDS = eINSTANCE.getGraphqlInputTypeDefinition_Fields();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlInputFieldImpl <em>Graphql Input Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlInputFieldImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlInputField()
     * @generated
     */
    EClass GRAPHQL_INPUT_FIELD = eINSTANCE.getGraphqlInputField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHQL_INPUT_FIELD__NAME = eINSTANCE.getGraphqlInputField_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_INPUT_FIELD__TYPE = eINSTANCE.getGraphqlInputField_Type();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlFieldImpl <em>Graphql Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlFieldImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlField()
     * @generated
     */
    EClass GRAPHQL_FIELD = eINSTANCE.getGraphqlField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHQL_FIELD__NAME = eINSTANCE.getGraphqlField_Name();

    /**
     * The meta object literal for the '<em><b>Args</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_FIELD__ARGS = eINSTANCE.getGraphqlField_Args();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_FIELD__TYPE = eINSTANCE.getGraphqlField_Type();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlTypeImpl <em>Graphql Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlTypeImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlType()
     * @generated
     */
    EClass GRAPHQL_TYPE = eINSTANCE.getGraphqlType();

    /**
     * The meta object literal for the '<em><b>Dtype</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_TYPE__DTYPE = eINSTANCE.getGraphqlType_Dtype();

    /**
     * The meta object literal for the '<em><b>Non Null</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHQL_TYPE__NON_NULL = eINSTANCE.getGraphqlType_NonNull();

    /**
     * The meta object literal for the '<em><b>Ntype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_TYPE__NTYPE = eINSTANCE.getGraphqlType_Ntype();

    /**
     * The meta object literal for the '<em><b>Ltype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_TYPE__LTYPE = eINSTANCE.getGraphqlType_Ltype();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlNamedTypeImpl <em>Graphql Named Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlNamedTypeImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlNamedType()
     * @generated
     */
    EClass GRAPHQL_NAMED_TYPE = eINSTANCE.getGraphqlNamedType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHQL_NAMED_TYPE__NAME = eINSTANCE.getGraphqlNamedType_Name();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlListTypeImpl <em>Graphql List Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlListTypeImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlListType()
     * @generated
     */
    EClass GRAPHQL_LIST_TYPE = eINSTANCE.getGraphqlListType();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlInputTypeImpl <em>Graphql Input Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlInputTypeImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlInputType()
     * @generated
     */
    EClass GRAPHQL_INPUT_TYPE = eINSTANCE.getGraphqlInputType();

    /**
     * The meta object literal for the '<em><b>Dtype</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_INPUT_TYPE__DTYPE = eINSTANCE.getGraphqlInputType_Dtype();

    /**
     * The meta object literal for the '<em><b>Non Null</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GRAPHQL_INPUT_TYPE__NON_NULL = eINSTANCE.getGraphqlInputType_NonNull();

    /**
     * The meta object literal for the '<em><b>Ntype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_INPUT_TYPE__NTYPE = eINSTANCE.getGraphqlInputType_Ntype();

    /**
     * The meta object literal for the '<em><b>Ltype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_INPUT_TYPE__LTYPE = eINSTANCE.getGraphqlInputType_Ltype();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlListInputTypeImpl <em>Graphql List Input Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlListInputTypeImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlListInputType()
     * @generated
     */
    EClass GRAPHQL_LIST_INPUT_TYPE = eINSTANCE.getGraphqlListInputType();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.ArgumentImpl <em>Argument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.ArgumentImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getArgument()
     * @generated
     */
    EClass ARGUMENT = eINSTANCE.getArgument();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARGUMENT__NAME = eINSTANCE.getArgument_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARGUMENT__TYPE = eINSTANCE.getArgument_Type();

    /**
     * The meta object literal for the '<em><b>Def Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARGUMENT__DEF_VALUE = eINSTANCE.getArgument_DefValue();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.GraphqlValueImpl <em>Graphql Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.GraphqlValueImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getGraphqlValue()
     * @generated
     */
    EClass GRAPHQL_VALUE = eINSTANCE.getGraphqlValue();

    /**
     * The meta object literal for the '<em><b>Sv</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_VALUE__SV = eINSTANCE.getGraphqlValue_Sv();

    /**
     * The meta object literal for the '<em><b>Ev</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_VALUE__EV = eINSTANCE.getGraphqlValue_Ev();

    /**
     * The meta object literal for the '<em><b>Cv</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPHQL_VALUE__CV = eINSTANCE.getGraphqlValue_Cv();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.SingleValueImpl <em>Single Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.SingleValueImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getSingleValue()
     * @generated
     */
    EClass SINGLE_VALUE = eINSTANCE.getSingleValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_VALUE__VALUE = eINSTANCE.getSingleValue_Value();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.ComplexValueImpl <em>Complex Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.ComplexValueImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getComplexValue()
     * @generated
     */
    EClass COMPLEX_VALUE = eINSTANCE.getComplexValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_VALUE__VALUE = eINSTANCE.getComplexValue_Value();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.EnumValueImpl <em>Enum Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.EnumValueImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getEnumValue()
     * @generated
     */
    EClass ENUM_VALUE = eINSTANCE.getEnumValue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENUM_VALUE__NAME = eINSTANCE.getEnumValue_Name();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.ListValueImpl <em>List Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.ListValueImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getListValue()
     * @generated
     */
    EClass LIST_VALUE = eINSTANCE.getListValue();

    /**
     * The meta object literal for the '<em><b>Values</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIST_VALUE__VALUES = eINSTANCE.getListValue_Values();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.ObjectValueImpl <em>Object Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.ObjectValueImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getObjectValue()
     * @generated
     */
    EClass OBJECT_VALUE = eINSTANCE.getObjectValue();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_VALUE__FIELDS = eINSTANCE.getObjectValue_Fields();

    /**
     * The meta object literal for the '{@link oda.graphql.language.graphqlidl.impl.ObjectFieldImpl <em>Object Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oda.graphql.language.graphqlidl.impl.ObjectFieldImpl
     * @see oda.graphql.language.graphqlidl.impl.GraphqlidlPackageImpl#getObjectField()
     * @generated
     */
    EClass OBJECT_FIELD = eINSTANCE.getObjectField();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OBJECT_FIELD__NAME = eINSTANCE.getObjectField_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_FIELD__VALUE = eINSTANCE.getObjectField_Value();

  }

} //GraphqlidlPackage
