/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.ui;

import oda.graphql.language.ui.AbstractGraphqlidlUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GraphqlidlUiModule extends AbstractGraphqlidlUiModule {
  public GraphqlidlUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
