/*
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGraphqlidlValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(oda.graphql.language.graphqlidl.GraphqlidlPackage.eINSTANCE);
		return result;
	}
	
}
