/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl.impl;

import oda.graphql.language.graphqlidl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class GraphqlidlFactoryImpl extends EFactoryImpl implements GraphqlidlFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static GraphqlidlFactory init()
  {
    try
    {
      GraphqlidlFactory theGraphqlidlFactory = (GraphqlidlFactory)EPackage.Registry.INSTANCE.getEFactory(GraphqlidlPackage.eNS_URI);
      if (theGraphqlidlFactory != null)
      {
        return theGraphqlidlFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new GraphqlidlFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlidlFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case GraphqlidlPackage.GRAPHQL_SCHEMA: return createGraphqlSchema();
      case GraphqlidlPackage.GRAPHQL_SCHEMA_DEFINITION: return createGraphqlSchemaDefinition();
      case GraphqlidlPackage.GRAPHQL_ROOT_QUERY: return createGraphqlRootQuery();
      case GraphqlidlPackage.GRAPHQL_TYPE_DEFINITION: return createGraphqlTypeDefinition();
      case GraphqlidlPackage.GRAPHQL_OBJECT_TYPE_DEFINITION: return createGraphqlObjectTypeDefinition();
      case GraphqlidlPackage.GRAPHQL_INTERFACE_TYPE_DEFINITION: return createGraphqlInterfaceTypeDefinition();
      case GraphqlidlPackage.GRAPHQL_SCALAR_TYPE_DEFINITION: return createGraphqlScalarTypeDefinition();
      case GraphqlidlPackage.GRAPHQL_EMUN_TYPE_DEFINITION: return createGraphqlEmunTypeDefinition();
      case GraphqlidlPackage.GRAPHQL_UNION_TYPE_DEFINITION: return createGraphqlUnionTypeDefinition();
      case GraphqlidlPackage.GRAPHQL_INPUT_TYPE_DEFINITION: return createGraphqlInputTypeDefinition();
      case GraphqlidlPackage.GRAPHQL_INPUT_FIELD: return createGraphqlInputField();
      case GraphqlidlPackage.GRAPHQL_FIELD: return createGraphqlField();
      case GraphqlidlPackage.GRAPHQL_TYPE: return createGraphqlType();
      case GraphqlidlPackage.GRAPHQL_NAMED_TYPE: return createGraphqlNamedType();
      case GraphqlidlPackage.GRAPHQL_LIST_TYPE: return createGraphqlListType();
      case GraphqlidlPackage.GRAPHQL_INPUT_TYPE: return createGraphqlInputType();
      case GraphqlidlPackage.GRAPHQL_LIST_INPUT_TYPE: return createGraphqlListInputType();
      case GraphqlidlPackage.ARGUMENT: return createArgument();
      case GraphqlidlPackage.GRAPHQL_VALUE: return createGraphqlValue();
      case GraphqlidlPackage.SINGLE_VALUE: return createSingleValue();
      case GraphqlidlPackage.COMPLEX_VALUE: return createComplexValue();
      case GraphqlidlPackage.ENUM_VALUE: return createEnumValue();
      case GraphqlidlPackage.LIST_VALUE: return createListValue();
      case GraphqlidlPackage.OBJECT_VALUE: return createObjectValue();
      case GraphqlidlPackage.OBJECT_FIELD: return createObjectField();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlSchema createGraphqlSchema()
  {
    GraphqlSchemaImpl graphqlSchema = new GraphqlSchemaImpl();
    return graphqlSchema;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlSchemaDefinition createGraphqlSchemaDefinition()
  {
    GraphqlSchemaDefinitionImpl graphqlSchemaDefinition = new GraphqlSchemaDefinitionImpl();
    return graphqlSchemaDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlRootQuery createGraphqlRootQuery()
  {
    GraphqlRootQueryImpl graphqlRootQuery = new GraphqlRootQueryImpl();
    return graphqlRootQuery;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlTypeDefinition createGraphqlTypeDefinition()
  {
    GraphqlTypeDefinitionImpl graphqlTypeDefinition = new GraphqlTypeDefinitionImpl();
    return graphqlTypeDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlObjectTypeDefinition createGraphqlObjectTypeDefinition()
  {
    GraphqlObjectTypeDefinitionImpl graphqlObjectTypeDefinition = new GraphqlObjectTypeDefinitionImpl();
    return graphqlObjectTypeDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlInterfaceTypeDefinition createGraphqlInterfaceTypeDefinition()
  {
    GraphqlInterfaceTypeDefinitionImpl graphqlInterfaceTypeDefinition = new GraphqlInterfaceTypeDefinitionImpl();
    return graphqlInterfaceTypeDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlScalarTypeDefinition createGraphqlScalarTypeDefinition()
  {
    GraphqlScalarTypeDefinitionImpl graphqlScalarTypeDefinition = new GraphqlScalarTypeDefinitionImpl();
    return graphqlScalarTypeDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlEmunTypeDefinition createGraphqlEmunTypeDefinition()
  {
    GraphqlEmunTypeDefinitionImpl graphqlEmunTypeDefinition = new GraphqlEmunTypeDefinitionImpl();
    return graphqlEmunTypeDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlUnionTypeDefinition createGraphqlUnionTypeDefinition()
  {
    GraphqlUnionTypeDefinitionImpl graphqlUnionTypeDefinition = new GraphqlUnionTypeDefinitionImpl();
    return graphqlUnionTypeDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlInputTypeDefinition createGraphqlInputTypeDefinition()
  {
    GraphqlInputTypeDefinitionImpl graphqlInputTypeDefinition = new GraphqlInputTypeDefinitionImpl();
    return graphqlInputTypeDefinition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlInputField createGraphqlInputField()
  {
    GraphqlInputFieldImpl graphqlInputField = new GraphqlInputFieldImpl();
    return graphqlInputField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlField createGraphqlField()
  {
    GraphqlFieldImpl graphqlField = new GraphqlFieldImpl();
    return graphqlField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlType createGraphqlType()
  {
    GraphqlTypeImpl graphqlType = new GraphqlTypeImpl();
    return graphqlType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlNamedType createGraphqlNamedType()
  {
    GraphqlNamedTypeImpl graphqlNamedType = new GraphqlNamedTypeImpl();
    return graphqlNamedType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlListType createGraphqlListType()
  {
    GraphqlListTypeImpl graphqlListType = new GraphqlListTypeImpl();
    return graphqlListType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlInputType createGraphqlInputType()
  {
    GraphqlInputTypeImpl graphqlInputType = new GraphqlInputTypeImpl();
    return graphqlInputType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlListInputType createGraphqlListInputType()
  {
    GraphqlListInputTypeImpl graphqlListInputType = new GraphqlListInputTypeImpl();
    return graphqlListInputType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Argument createArgument()
  {
    ArgumentImpl argument = new ArgumentImpl();
    return argument;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlValue createGraphqlValue()
  {
    GraphqlValueImpl graphqlValue = new GraphqlValueImpl();
    return graphqlValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SingleValue createSingleValue()
  {
    SingleValueImpl singleValue = new SingleValueImpl();
    return singleValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComplexValue createComplexValue()
  {
    ComplexValueImpl complexValue = new ComplexValueImpl();
    return complexValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnumValue createEnumValue()
  {
    EnumValueImpl enumValue = new EnumValueImpl();
    return enumValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ListValue createListValue()
  {
    ListValueImpl listValue = new ListValueImpl();
    return listValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectValue createObjectValue()
  {
    ObjectValueImpl objectValue = new ObjectValueImpl();
    return objectValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ObjectField createObjectField()
  {
    ObjectFieldImpl objectField = new ObjectFieldImpl();
    return objectField;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public GraphqlidlPackage getGraphqlidlPackage()
  {
    return (GraphqlidlPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static GraphqlidlPackage getPackage()
  {
    return GraphqlidlPackage.eINSTANCE;
  }

} //GraphqlidlFactoryImpl
