/**
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.graphqlidl.impl;

import oda.graphql.language.graphqlidl.ComplexValue;
import oda.graphql.language.graphqlidl.EnumValue;
import oda.graphql.language.graphqlidl.GraphqlValue;
import oda.graphql.language.graphqlidl.GraphqlidlPackage;
import oda.graphql.language.graphqlidl.SingleValue;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Graphql Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link oda.graphql.language.graphqlidl.impl.GraphqlValueImpl#getSv <em>Sv</em>}</li>
 *   <li>{@link oda.graphql.language.graphqlidl.impl.GraphqlValueImpl#getEv <em>Ev</em>}</li>
 *   <li>{@link oda.graphql.language.graphqlidl.impl.GraphqlValueImpl#getCv <em>Cv</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GraphqlValueImpl extends MinimalEObjectImpl.Container implements GraphqlValue
{
  /**
   * The cached value of the '{@link #getSv() <em>Sv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSv()
   * @generated
   * @ordered
   */
  protected SingleValue sv;

  /**
   * The cached value of the '{@link #getEv() <em>Ev</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEv()
   * @generated
   * @ordered
   */
  protected EnumValue ev;

  /**
   * The cached value of the '{@link #getCv() <em>Cv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCv()
   * @generated
   * @ordered
   */
  protected ComplexValue cv;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GraphqlValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GraphqlidlPackage.Literals.GRAPHQL_VALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SingleValue getSv()
  {
    return sv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSv(SingleValue newSv, NotificationChain msgs)
  {
    SingleValue oldSv = sv;
    sv = newSv;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GraphqlidlPackage.GRAPHQL_VALUE__SV, oldSv, newSv);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSv(SingleValue newSv)
  {
    if (newSv != sv)
    {
      NotificationChain msgs = null;
      if (sv != null)
        msgs = ((InternalEObject)sv).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GraphqlidlPackage.GRAPHQL_VALUE__SV, null, msgs);
      if (newSv != null)
        msgs = ((InternalEObject)newSv).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GraphqlidlPackage.GRAPHQL_VALUE__SV, null, msgs);
      msgs = basicSetSv(newSv, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GraphqlidlPackage.GRAPHQL_VALUE__SV, newSv, newSv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnumValue getEv()
  {
    if (ev != null && ev.eIsProxy())
    {
      InternalEObject oldEv = (InternalEObject)ev;
      ev = (EnumValue)eResolveProxy(oldEv);
      if (ev != oldEv)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GraphqlidlPackage.GRAPHQL_VALUE__EV, oldEv, ev));
      }
    }
    return ev;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnumValue basicGetEv()
  {
    return ev;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEv(EnumValue newEv)
  {
    EnumValue oldEv = ev;
    ev = newEv;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GraphqlidlPackage.GRAPHQL_VALUE__EV, oldEv, ev));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ComplexValue getCv()
  {
    return cv;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCv(ComplexValue newCv, NotificationChain msgs)
  {
    ComplexValue oldCv = cv;
    cv = newCv;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GraphqlidlPackage.GRAPHQL_VALUE__CV, oldCv, newCv);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCv(ComplexValue newCv)
  {
    if (newCv != cv)
    {
      NotificationChain msgs = null;
      if (cv != null)
        msgs = ((InternalEObject)cv).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GraphqlidlPackage.GRAPHQL_VALUE__CV, null, msgs);
      if (newCv != null)
        msgs = ((InternalEObject)newCv).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GraphqlidlPackage.GRAPHQL_VALUE__CV, null, msgs);
      msgs = basicSetCv(newCv, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GraphqlidlPackage.GRAPHQL_VALUE__CV, newCv, newCv));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GraphqlidlPackage.GRAPHQL_VALUE__SV:
        return basicSetSv(null, msgs);
      case GraphqlidlPackage.GRAPHQL_VALUE__CV:
        return basicSetCv(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GraphqlidlPackage.GRAPHQL_VALUE__SV:
        return getSv();
      case GraphqlidlPackage.GRAPHQL_VALUE__EV:
        if (resolve) return getEv();
        return basicGetEv();
      case GraphqlidlPackage.GRAPHQL_VALUE__CV:
        return getCv();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GraphqlidlPackage.GRAPHQL_VALUE__SV:
        setSv((SingleValue)newValue);
        return;
      case GraphqlidlPackage.GRAPHQL_VALUE__EV:
        setEv((EnumValue)newValue);
        return;
      case GraphqlidlPackage.GRAPHQL_VALUE__CV:
        setCv((ComplexValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GraphqlidlPackage.GRAPHQL_VALUE__SV:
        setSv((SingleValue)null);
        return;
      case GraphqlidlPackage.GRAPHQL_VALUE__EV:
        setEv((EnumValue)null);
        return;
      case GraphqlidlPackage.GRAPHQL_VALUE__CV:
        setCv((ComplexValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GraphqlidlPackage.GRAPHQL_VALUE__SV:
        return sv != null;
      case GraphqlidlPackage.GRAPHQL_VALUE__EV:
        return ev != null;
      case GraphqlidlPackage.GRAPHQL_VALUE__CV:
        return cv != null;
    }
    return super.eIsSet(featureID);
  }

} //GraphqlValueImpl
