/*
 * generated by Xtext 2.10.0
 */
package oda.graphql.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GraphqlidlStandaloneSetup extends GraphqlidlStandaloneSetupGenerated {

	def static void doSetup() {
		new GraphqlidlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
