/*
 * generated by Xtext 2.10.0
 */
package oda.graphql.language.parser.antlr;

import com.google.inject.Inject;
import oda.graphql.language.parser.antlr.internal.InternalGraphqlidlParser;
import oda.graphql.language.services.GraphqlidlGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GraphqlidlParser extends AbstractAntlrParser {

	@Inject
	private GraphqlidlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT", "RULE_COMMA", "RULE_COMMENT");
	}
	

	@Override
	protected InternalGraphqlidlParser createParser(XtextTokenStream stream) {
		return new InternalGraphqlidlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GraphqlSchema";
	}

	public GraphqlidlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GraphqlidlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
